import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'uno.css'
import React from "react";
import '@unocss/reset/tailwind.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <div className="bg-[#a8d212ff] h-[100px] w-[200px]  text-[#dbdde8ff]">22222</div>
    {children}
    </body>
    </html>
  );
}
